### ISSUE TITLE
menu_calibration.cfg incorrect type specified 'deck' is not a valid choice

### ISSUE THREAD

**Issue by TheBlackMini** [fl0r1s/cr10_klipper#1]
Choice 'deck' for option 'type' in section 'menu __calibration_bed_mesh_calibrate' is not a valid choice

Available menu elements:
  item - purely visual element
  command - same like 'item' but with gcode trigger
  input - same like 'command' but has value changing capabilities
  list - menu element container, with entry and exit gcode triggers
  vsdcard - same as 'list' but will append files from virtual sdcard

I suspect that this is supposed to be 'command'??

**Comment by TheBlackMini** [comment]
Also, enter_gcode isn't valid either.

**Comment by breakingflower** [comment]
This dates from some time ago, when it was still an option. 

It should be command, and the gcode should be a simple G29, as thats defined in generic/macros.cfg . I have removed the other options as I dont use them. Thanks for intel! 

Fixed in master.
